PaloAltoNetworks/bahamut

- Gopkg.toml
- pubsub_nats_test.go
This PR adds unit test coverage for the `Subscribe` method by bringing up a real NATS server on loopback interface as per suggested by the upstream NATS Go client maintainer [here](https://github.com/nats-io/nats.go/issues/467#issuecomment-493632703). This is actually how the upstream Go NATS client tests their implementation.
- should successfully subscribe to topic and receive a publication in provided channel
- should NOT receive anything in publication channel that cannot be decoded into a publication
- should respond back with an ACK message to all publications that expect an ACK response
- should be able to set a custom response using the NATSOptSubscribeReplyer option to all publications that expect a response
> new: unit tests for PubSubClient NATS implementation Subscribe method

- pubsub_nats_test.go
This test covers the behaviour where `Subscribe` fails due to an error - https://github.com/aporeto-inc/bahamut/blob/master/pubsub_nats.go#L131
Notice what this implies for the consumer of this API, they must either:
- pass in a buffered error channel
- start reading from the error channel prior to calling `Subscribe`
Otherwise if they hit this error condition, they would be blocked forever as writing to an unbuffered channel will indefinitely block unless there is a reader on the other side...
> new: add test coverage for scenario: should receive an error in errors channel if subscribing fails for any reason

- pubsub_nats.go
- pubsub_nats_options.go
- pubsub_nats_test.go
This PR introduces a new option to the NATS pubsub `Publish` method: `NATSOptRespondToChannel`
This option allows clients to receive the response `*Publication` to a channel they configure when using the [NATS request-reply messaging pattern](https://nats.io/documentation/concepts/nats-req-rep/). This is particularly useful in situations where the client is publishing something within an HTTP handler and they need to block and wait for a reply so they can use the response message to craft an appropriate HTTP response (_e.g. Aporeto automations handling webhooks!_).
```go
responseCh := make(chan *Publication)
errorCh := make(chan error)
ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
defer cancel()
go func() {
if err := p.pubsub.Publish(pub, …
```
> new: add ability for caller to get back received raw *nats.Msg to a channel

- publication.go
- pubsub_nats.go
- pubsub_nats_options.go
- pubsub_nats_options_test.go
- pubsub_nats_test.go
This PR adds the ability to distinguish between different Publish requests when using the NATS request-reply messaging pattern. Our existing `PubSubOptPublish` options are impacted as follows: 
 
When configured, it will set the ResponseMode field of the Publication to “ReplyWithACK”. The side effect of this is that caller of Publish will now block until an ACK is received or the supplied context deadline is reached. As a result of this option our implementation of Subscribe will now need to look for this new ResponseMode attribute when consuming messages to determine whether it needs to respond back with an ACK - the value would be set to “ReplyWithACK”. This option is mutually exclusive with the `NATSOptRespondToChannel` option.
 
When configured, it will set the ResponseMode field of …
> NATS PubSub  - adds ability to distinguish between different Publish requests

- publication.go
- publication_test.go
- pubsub_nats.go
- pubsub_nats_options.go
- pubsub_nats_options_test.go
- pubsub_nats_test.go
---
This builds on https://github.com/aporeto-inc/bahamut/pull/59 by modifying the NATS `Subscribe` implementation to consume the new `ResponseMode` attribute serialized into the `Publication` message
- Subscriber subscribes to a subject they are interested in receiving Publications for
- When Subscriber receives a Publication, it checks whether a response was even expected (_by examining the raw NATS message's `Reply` field, then it examines the `ResponseMode` attribute of the publication to determine the type of response the client is expecting:
- **ACK response**: subscriber responds right away prior to sending the publication to the pubs channel
- **Publication response**: a response channel is created and then a new goroutine is spawned waiting to read of this channel. The client …
> new: add ability for subscriber to respond back to publication AFTER processing

- publication.go
- publication_test.go
- pubsub_nats.go
- pubsub_nats_options_test.go
- pubsub_nats_test.go
This fixes a bug where the client's call to `Reply` can block indefinitely if the client calls `Reply` **AFTER** the response deadline has been reached.
This would happen because [the goroutine running the response handler](https://github.com/aporeto-inc/bahamut/blob/master/pubsub_nats.go#L125) would terminate [after the response deadline is hit](https://github.com/aporeto-inc/bahamut/blob/master/pubsub_nats.go#L139). As a result, when the client calls the `Reply` method, they will be [attempting to write to a channel that no longer has a receiver](https://github.com/aporeto-inc/bahamut/blob/master/publication.go#L181) and wait until the end of time 😢
> fixes bug where client responds to a publication that has reached its reply timeout

- dispatchers.go
- dispatchers_test.go
Issue: https://github.com/aporeto-inc/bahamut/issues/64
> resolves #64 by checking the type of ctx.outputData

- config.go
- options.go
- options_test.go
- rest_server.go
- rest_server_helpers.go
- rest_server_helpers_test.go
- websocket_server.go
bahamut uses the HTTP Header `Origin` to set the CORS allowed origin. If it finds no header, it uses `*`.
This patch adds an option `OptCORSOrigin(string)` that allows to force using the given strict as CORS allowed origin
> new: add option to provide strict CORS origin

- bahamut.go
- config.go
- handlers.go
- handlers_test.go
- options.go
- options_test.go
- rest_server.go
- rest_server_helpers.go
- websocket_server.go
adds the option `OptMarshallers(marshallers map[elemental.Identity]CustomMarshaller) ` to pass a list of custom marshalers that will be used to encode the response using a custom marshaling process
> new: support for custom marshallers

- .gitignore
- authorizer/mtls/authorizer_test.go
- interfaces.go
- websocket_push_session.go
- websocket_push_session_test.go
- websocket_server.go
- websocket_server_test.go
----
- ⚠️ **Breaking change**: add new method to the `Session` interface, `PushConfig`, to make it possible to retrieve the push config currently active on the session.
Note: this was done so that [this callback](https://github.com/aporeto-inc/bahamut/blob/69c31e07899a7719b33888c903b15ef507a7ac62/interfaces.go#L243):
1.  has enough context to decide whether it is worth parsing the entire identifiable
2. be able to do fine-grain identity filtering via https://github.com/aporeto-inc/elemental/blob/master/matcher.go#L10
- :fire: Remove usage of deprecated type `elemental.PushFilter`; replaced with the re-named equivalent `elemental.PushConfig`
- Parse the identity filters upon receipt of a `elemental.PushConfig` to avoid having to parse them on each push event received by the push server
- …
> Add support for fine-grained websocket filtering

- context.go
- context_test.go
- gateway/gateway.go
- gateway/gateway_test.go
- gateway/options.go
- gateway/options_test.go
- interfaces.go
- rest_server.go
Setting a custom ResponseWriter in the bahamut.Context let the user write the raw http response to the client using the standard http.ResponseWritter.
> new: support for custom response writer

- context.go
- context_test.go
- dispatchers.go
- dispatchers_test.go
- interfaces.go
You can now use ctx.SetDisableOutputDataPush(true) to prevent Bahamut from pushing automatically the content of the context's OutputData.
> new: support for disabling auto pushing

- pubsub_nats.go
This patch removes the insert of nat.sSecure option if no tlsConfig is passed
> fixed: nats pubsub client whithout TLS

- gateway/upstreamer/push/options.go
- gateway/upstreamer/push/options_test.go
- gateway/upstreamer/push/upstreamer.go
- gateway/upstreamer/push/upstreamer_test.go
This option will allow us to decide when to apply the Load based balancing and allow custom implementation to be passed.
There is a flaw in the load based balancing as the load is reported by the endpoint every ping time (3s). It might be stale.
With small deployment, this is leads to very bad performances as all the traffic is going to one instance then to the other.
By setting a threshold to 6, the load based balancing is not done if the number of endpoint is < 6, instead a random one is picked. With that setup we triple at least the throughput performances.
> new/upstreamer: Added an OptionLoadBasedBalancer

- handlers.go
- handlers_test.go
this patch simplifies very old code that was using go routine and channels in one of the lowest level dispatching function. It turns out thes go routines are not only unecessary, but they were killing the peformances under heavy load
> fixed: simplify runDispatcher

- gateway/gateway.go
- gateway/listener.go
In order to do a fast efficient TCP rate limiting we are setting the SO_LINGER flag to 0 so we send a RST packed right away.
I had to move the newLimitedListener closer to the TCPListener as the tls.Conn cannot access the underlying net.TCPConn
> impr/gateway: Move the newLimitedListener higher un the chain so its at TCP level.

- dispatchers.go
- dispatchers_test.go
During a patch update, we were missing a check on the data which allowed a PATCH API request to bypass traditional validation. We should now have all the bases covered. :)
> Fixes: https://github.com/aporeto-inc/aporeto-devs/issues/812
> Fixed: Validate patchable updates if checks exist

- bahamut.go
- config.go
- options.go
- options_test.go
- websocket_server.go
- websocket_server_test.go
This PR adds an optional ability to publish to specific subject hierarchies of the configured topic of the push server via a new functional option `OptPushServerEnableSubjectHierarchies`.
The goal is to provide subscribers the ability to receive only events they care about instead of having them be required to add logic to ignore events they are not interested in.
**For example:**
If the push server topic has been set to `global-events` and the server is about to push a "create" event w/ an identity value of "apples", enabling this option, would cause the push server to target a new publication to the subject `global-events.apples.create`, **INSTEAD OF** `global-events`.
See https://docs.nats.io/nats-concepts/subjects for more details.
- https://redlock.atlassian.net/browse/CNS-340
- …
> CNS-340 - add ability to publish to specific subject hierarchies

- gateway/gateway.go
- gateway/options.go
- gateway/options_test.go
- gateway/rewriters.go
- gateway/rewriters_test.go
For service to service all going through an internal gateway, one might find useful to keep the original client IP.
> impr/gateway: Add a way to preserve client IP when forwarded

- gateway/upstreamer/push/upstreamer.go
- gateway/upstreamer/push/upstreamer_options.go
- gateway/upstreamer/push/upstreamer_options_test.go
- gateway/upstreamer/push/upstreamer_test.go
This option can be used to set an additional topic for services ping. This allows to use different topic to announce services that should be served globally
> new/gateway/push: added a global topic option for service ping

- .travis.yml
- authorizer/mtls/authorizer.go
- gateway/gateway.go
- gateway/gateway_test.go
- gateway/options.go
- gateway/options_test.go
- gateway/utils.go
- gateway/utils_test.go
- CORS: improve default and handling
- CORS: differentiate `*` and the `mirror` functionality
- CORS: add an option to control the general sending of`Access-Control-Allow-Credentials` header
- CORS: do not send `Access-Control-Allow-Credentials: true` is CORS origin is set to `*` or empty
- MTLS: add comment on how to implement CRL using the `VerifierFunc`
> fixed: security audit findings

- gateway/gateway.go
- gateway/rewriters.go
- gateway/rewriters_test.go
This patch adds a header marker in the incoming request that are planned to be upgraded to websockets. This marker will be used to decide to set X-Forwarded-For header on the internal request rewriter.
This will make sure the ws backend receives a correct X-Forwarded-For header
> fixed: oxy not forwarding IP info to ws backend

- gateway/upstreamer/push/movingaverage.go
- gateway/upstreamer/push/movingaverage_test.go
- gateway/upstreamer/push/upstreamer.go
- gateway/upstreamer/push/upstreamer_distribution_test.go
```
WARNING: DATA RACE
Read at 0x00c0007e1a90 by goroutine 235:
go.aporeto.io/bahamut/gateway/upstreamer/push.(*movingAverage).insertValue()
/tmp/build/ae5c2d4a/go/pkg/mod/go.aporeto.io/bahamut@v1.112.1-0.20210511234020-d223af0361d8/gateway/upstreamer/push/movingaverage.go:47 +0x105
go.aporeto.io/bahamut/gateway/upstreamer/push.(*Upstreamer).CollectLatency()
/tmp/build/ae5c2d4a/go/pkg/mod/go.aporeto.io/bahamut@v1.112.1-0.20210511234020-d223af0361d8/gateway/upstreamer/push/upstreamer.go:543 +0x9d
go.aporeto.io/bahamut/gateway.(*gateway).ServeHTTP()
/tmp/build/ae5c2d4a/go/pkg/mod/go.aporeto.io/bahamut@v1.112.1-0.20210511234020-d223af0361d8/gateway/gateway.go:540 +0x160c
net/http.serverHandler.ServeHTTP()
/usr/local/go/src/net/http/server.go:2887 +0xca
net/http.(*conn).serve() …
```
> fix/race: Fix a data race access to the moving average pointer

- .github/workflows/build-go.yaml
Work towards support go 1.17.x while keeping older support.
> Update: Support go 1.17 and split linter version

- handlers.go
- handlers_test.go
Previously when calling context.SetStatusCode and not having any output data was always overwrite to No Content. This patch ensure that No content is set only if the user did not set a custom code or set to status ok
> fixed: status code overwritten to No Content even if user set it before

- websocket_push_session_mock.go
- websocket_push_session_mock_test.go
This patch fixes the MockPushSession missing PushSession interface method DirectPush
> fixed/mocksession: missing interface method DirectPush

- config.go
- options.go
- options_test.go
- rest_server.go
Adds option `OptMTLSVerifyPeerCertificates' to allow configuring a custom client certificate verification function.
> new/options: added option to set tls.Config.VerifyPeerCertificates

- gateway/extractors.go
- gateway/extractors_test.go
This patch adds a new function NewDefaultSourceExtractor(string) that
returns a SourceExtractor that can also look for a cookie with the given
name to discriminate the source of a request.
> gateway/sourceextractor: add way to consider cookie.

- go.mod
- go.sum
During the install/install run for Apomux on a M1 mac, gopsutil is failing to build:
```
../../../pkg/mod/github.com/shirou/gopsutil@v2.20.6+incompatible/process/process_darwin.go:576:34: undefined: KinfoProc
../../../pkg/mod/github.com/shirou/gopsutil@v2.20.6+incompatible/process/process_darwin.go:577:8: undefined: KinfoProc
../../../pkg/mod/github.com/shirou/gopsutil@v2.20.6+incompatible/process/process_darwin.go:590:32: undefined: KinfoProc
../../../pkg/mod/github.com/shirou/gopsutil@v2.20.6+incompatible/process/process_darwin.go:594:62: undefined: KinfoProc
../../../pkg/mod/github.com/shirou/gopsutil@v2.20.6+incompatible/process/process_darwin.go:596:11: undefined: KinfoProc
```
This dependency is coming from Apomux <- Backend <- Bahamut <- Gopsutil
According to this kubernetes issue, …
> Draft: Update gopsutil due to issues on M1 mac during Apomux install script

- Makefile
- gateway/upstreamer/push/notifier.go
- gateway/upstreamer/push/notifier_options.go
- gateway/upstreamer/push/notifier_options_test.go
- gateway/upstreamer/push/notifier_test.go
- gateway/upstreamer/push/ping.go
- gateway/upstreamer/push/upstreamer.go
- gateway/upstreamer/push/upstreamer_distribution_test.go
- gateway/upstreamer/push/upstreamer_test.go
- gateway/upstreamer/push/utils.go
- gateway/upstreamer/push/utils_test.go
This patch allows services to announce a desired prefix for the gqteway to route traffic to them.
Add OptionNotifierPrefix("myprefix") to a service, and the gateway will only route apis prefixed by "_myprefix" (the "_" is mandatory in the URL in order to efficiently distinguish prefixes)
It also adds OptionNotifierAPIPrivateOverrides that allows to change the private flag for a particular route.
> new: support for api prefixes

- gateway/gateway_test.go
- health_server_test.go
- metrics.go
- metrics_prometheus.go
- metrics_prometheus_test.go
This patches fixes a bug where the sanitization function of the prometheus metric manager was not correctly handling the given path if it was containing a '_prefix'. This patch fixes this issue and adds tests.
The parameter 'url' of the interface MetricManager.MeasureRequest has also been renamed to 'path' for better usage clarity.
> fixed/metrics/prometheus: correctly handle prefix

- gateway/errors_test.go
- gateway/upstreamer/push/notifier_test.go
- go.mod
- go.sum
- publication.go
1. removes the final dependancy on github.com/vulcand/oxy V1 which requires gocheck and that requires Bazaar VCS.  Oxy V2 is the current version and does not import gocheck, thus eliminating the need for Bazaar VCS (bzr) 
2. Fixes a data race condition in the publisher
1. removes the need for the bazaar binary when everything else uses git 
2. Fixes a data race in the publisher. 
using `make test` 
Output after the fix is applied: 
```shell
$ make test
go test ./... -race -cover -covermode=atomic -coverprofile=unit_coverage.out
ok      go.aporeto.io/bahamut   107.834s        coverage: 90.8% of statements
ok      go.aporeto.io/bahamut/authorizer/mtls   51.784s coverage: 97.7% of statements
ok      go.aporeto.io/bahamut/authorizer/simple 51.676s coverage: 100.0% of statements
ok …
```
> fix data race and remove oxy v1
